#!/bin/bash

blockMesh
for (( i=0; i <= 31; i++ ))
do
rm -rf processor$i
done
decomposePar
mpirun -np 32 snappyHexMesh -overwrite -parallel
reconstructParMesh -constant -mergeTol 1e-06
for (( i=0; i <= 31; i++ ))
do
rm -rf processor$i
done
foamToVTK
