#!/bin/bash

for (( i=0; i <= 15; i++ ))
do
rm -rf processor$i
done
decomposePar
mpirun -np 16 rhoCentralFoam -parallel 
reconstructPar -latestTime
foamToVTK
for (( i=0; i <= 15; i++ ))
do
rm -rf processor$i
done